#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
 yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
 sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                on             \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff00ff00     \
    window_border_width          1              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  2              \
    bottom_padding               2              \
    left_padding                 2              \
    right_padding                2              \
    window_gap                   2              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^System Preferences$"    sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$"    sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$"                sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$"          sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$"    sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$"      sticky=on layer=above manage=off
yabai -m rule --add app="^zoom.us$"               sticky=on layer=above manage=off
yabai -m rule --add app="Outlook"                 sticky=off layer=above manage=off space=5 
yabai -m rule --add app="^Logi Options$"          manage=off
yabai -m rule --add app="Alacritty"               space=2
yabai -m rule --add app="Code"                    space=3
yabai -m rule --add app="Slack"                   space=4
yabai -m rule --add app="Obsidian"                space=6
#yabai -m signal --add event=space_changed  action="yabai -m window --focus first"
echo "yabai configuration loaded.."
